name: Github Action Example using Ansible
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy_code:
    runsuses: actions/checkout@v4        

    steps:
      - name: Run Ansible playbook
        with:
          playbook: AnsibleProject/playbook.yml
          inventory: localhost
