name: Github Action Example using Ansible
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy_code:
    runs-on: ubuntu-latest    

    steps:
      - name: GitHub code checkout
        uses: actions/checkout@master

      - name: Running Ansible playbook 
        run: cd AnsibleProject && ansible-playbook playbook.yaml

