name: Github Action Example using Ansible
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy_code:
    runs-on: ubuntu-latest    

    steps:
      - name: Run Ansible playbook
        uses: actions/checkout@v4    
        with:
          playbook: AnsibleProject/playbook.yaml
          # inventory: localhost
